/*
 * Copyright (C) 2015 World Intellectual Property Organization (WIPO).
 * All Rights Reserved.
 *
 * This file is part of WIPO Connect.
 *
 *
 * @author Fincons
 *
 */
package org.wipo.connect.echoservice;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2017-05-31T17:33:48.831+02:00
 * Generated source version: 2.7.13
 *
 */
@HandlerChain(file = "/handlers.xml")
@WebService(targetNamespace = "http://echoService.connect.wipo.org", name = "echoServicePort")
@XmlSeeAlso({org.wipo.connect.echoservice.types.ObjectFactory.class, org.wipo.connect.common.input.ObjectFactory.class, org.wipo.connect.common.output.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EchoServicePort {

    @WebMethod(action = "http://echoService.connect.wipo.org/NewOperation")
    @WebResult(name = "EchoResponse", targetNamespace = "http://types.echoService.connect.wipo.org", partName = "parameters")
    public org.wipo.connect.echoservice.types.EchoResponse echo(
        @WebParam(partName = "parameters", name = "EchoRequest", targetNamespace = "http://types.echoService.connect.wipo.org")
        org.wipo.connect.echoservice.types.EchoRequest parameters
    );
}
