/*
 * Copyright (C) 2015 World Intellectual Property Organization (WIPO).
 * All Rights Reserved.
 *
 * This file is part of WIPO Copyright Connection (WCC).
 *
 *
 * @author Fincons
 *
 */
package org.wipo.connect.interestedparty.interestedpartyservice;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.13 2017-06-06T16:28:09.237+02:00 Generated source version: 2.7.13
 *
 */
@HandlerChain(file = "/handlers.xml")
@WebService(targetNamespace = "http://interestedPartyService.interestedParty.connect.wipo.org", name = "InterestedPartyServicePort")
@XmlSeeAlso({ org.wipo.connect.interestedparty.response.ObjectFactory.class, org.wipo.connect.common.input.ObjectFactory.class, org.wipo.connect.common.output.ObjectFactory.class,
	org.wipo.connect.interestedparty.request.ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InterestedPartyServicePort {

    @WebMethod(action = "http://interestedPartyService.connect.wipo.org/InterestedPartyService/getElaborationResult")
    @WebResult(name = "IRElaborationResponse", targetNamespace = "http://response.interestedParty.connect.wipo.org", partName = "IRElaborationResponse")
    public org.wipo.connect.interestedparty.response.IRElaborationResponse getElaborationResult(
	    @WebParam(partName = "ElaborationResultRequest", name = "IRElaborationRequest", targetNamespace = "http://request.interestedParty.connect.wipo.org") org.wipo.connect.interestedparty.request.IRElaborationRequest elaborationResultRequest);

    @WebMethod(action = "http://interestedPartyService.connect.wipo.org/InterestedPartyService/getInterestedPartyList")
    @WebResult(name = "IpLookupResponse", targetNamespace = "http://response.interestedParty.connect.wipo.org", partName = "InterestedPartyLookupResponse")
    public org.wipo.connect.interestedparty.response.IpLookupResponse getInterestedPartyList(
	    @WebParam(partName = "InterestedPartyLookupRequest", name = "IpLookupRequest", targetNamespace = "http://request.interestedParty.connect.wipo.org") org.wipo.connect.interestedparty.request.IpLookupRequest interestedPartyLookupRequest);

    @WebMethod(action = "http://interestedPartyService.connect.wipo.org/InterestedPartyService/registerInternationally")
    @WebResult(name = "InternationallyRegisterResponse", targetNamespace = "http://response.interestedParty.connect.wipo.org", partName = "IpInterestedPartyDetailsResponse")
    public org.wipo.connect.interestedparty.response.InternationallyRegisterResponse registerInternationally(
	    @WebParam(partName = "IpInterestedPartyDetailsRequest", name = "InternationallyRegisterRequest", targetNamespace = "http://request.interestedParty.connect.wipo.org") org.wipo.connect.interestedparty.request.InternationallyRegisterRequest ipInterestedPartyDetailsRequest);

    @WebMethod(action = "http://interestedPartyService.connect.wipo.org/InterestedPartyService/getNameList")
    @WebResult(name = "NameLookupResponse", targetNamespace = "http://response.interestedParty.connect.wipo.org", partName = "RoNameLookupResponse")
    public org.wipo.connect.interestedparty.response.NameLookupResponse getNameList(
	    @WebParam(partName = "RoNameLookupRequest", name = "NameLookupRequest", targetNamespace = "http://request.interestedParty.connect.wipo.org") org.wipo.connect.interestedparty.request.NameLookupRequest roNameLookupRequest);

    @WebMethod(action = "http://interestedPartyService.connect.wipo.org/InterestedPartyService/getInterestedPartyDetails")
    @WebResult(name = "IpDetailsResponse", targetNamespace = "http://response.interestedParty.connect.wipo.org", partName = "InterestedPartyDetailsResponse")
    public org.wipo.connect.interestedparty.response.IpDetailsResponse getInterestedPartyDetails(
	    @WebParam(partName = "InterestedPartyDetailsRequest", name = "IpDetailsRequest", targetNamespace = "http://request.interestedParty.connect.wipo.org") org.wipo.connect.interestedparty.request.IpDetailsRequest interestedPartyDetailsRequest);
}
